client_id = "fd406591b1a0aacd324bf6b01c0b9a53"
name = "Dashboard Analytics"
application_url = "https://dashboard-analytic-six.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "meprotech-dev.myshopify.com"

[auth]
redirect_urls = [
  "https://dashboard-analytic-six.vercel.app/auth/callback"
]

[access_scopes]
scopes = "read_orders,read_products,write_products"
use_legacy_install_flow = false

[webhooks]
api_version = "2024-10"

[[webhooks.subscriptions]]
topics = ["customers/data_request"]
uri = "/webhooks/customers-data-request"

[[webhooks.subscriptions]]
topics = ["customers/redact"]
uri = "/webhooks/customers-redact"

[[webhooks.subscriptions]]
topics = ["shop/redact"]
uri = "/webhooks/shop-redact"